### ISSUE TITLE
Date translation formatting

### ISSUE THREAD

**Issue by Lrochefort** [nuxt-modules/i18n#1015]
Is it possible to assign a **format** to the dateTime format for a specific language?

Let's say I have this in my datetime formats file for French:

```
fr: {
    short1: {
      year: 'numeric',
      month: 'numeric',
      day: 'numeric'
    },
    long: {
      year: 'numeric',
      month: 'numeric',
      day: 'numeric',
      weekday: 'short',
      hour: 'numeric',
      minute: 'numeric'
    }
  }
```
If I use ```<p>{{ $d(new Date(), 'short1') }}</p>```, it returns **07/01/2021**. 
I'd like to see **2021-01-07** instead.

Any help appreciated!

**Comment by rchl** [comment]
This is functionality provided by the `vue-i18n` package that this module uses internally so it's documented at http://kazupon.github.io/vue-i18n/guide/datetime.html .

As far as I can see France uses day/month/year format so the result you are getting is correct for that locale.

The `$d` API uses the `Intl.DateTimeFormat` browser API so the formatting of the date is determined by that API and dependant on the provided locale and you can't change it other than forcing a specific locale that uses your expected format. But I would think twice before doing that since the whole point of using a locale-specific API is to format the date according to the format that the specific locale uses.

**Comment by Lrochefort** [comment]
@rchl Thank you for your quick reply.
