### ISSUE TITLE
Property 'code' does not exist on type 'string | LocaleObject'.

### ISSUE THREAD

**Issue by jairoblatt** [nuxt-modules/i18n#1024]
I have some problems like this during my application, does anyone know how to solve it?
"any" was defined just for typescript to stop reporting the error, but I would like something more solid.

#### Code example
```sh  
const currentLocale = this.$i18n.locales?.find( ({ code }) => code === this.$i18n.getLocaleCookie()); 
```

**Comment by iifawzi** [comment]
Hi @jairoblatt, your code looks good for me, can you provide more info? What does your locales' array looks like? It must be an array of objects, and each includes code property. 

btw, you can access all the properties of the current locale through the `localeProperties` property if an array of objects is used. check https://i18n.nuxtjs.org/options-reference.

**Comment by rchl** [comment]
This is a type-checking error so it's not really relevant what the actual locales array looks like.

The error like:
```
Property 'code' does not exist on type 'string | LocaleObject'
```

will indeed trigger for a code like:

```js
const currentLocale = this.$i18n.locales?.find( ({ code }) => code === this.$i18n.getLocaleCookie()); 
```

since the `locales` array is defined to contain either just strings or objects and in the case of strings, there will be no `code` property.

You need to do add some type-guards to make typechecking happy. For example:

```js
const currentLocale = this.$i18n.locales?.find(locale => typeof (locale) !== 'string' && locale.code === this.$i18n.getLocaleCookie())
```

As @iifawzi mentioned, it will be easier to just use `this.$i18n.localeProperties` object although that change is not released at the time of writing this. I will release it right now.

**Comment by rchl** [comment]
`localeProperties` is now released in https://github.com/nuxt-community/i18n-module/releases/tag/v6.18.0
