### ISSUE TITLE
Access $t from outside this (Global $t function)

### ISSUE THREAD

**Issue by kamerat** [nuxt-modules/i18n#1026]
I have a use case where I would like to translate keys in places like:
* props
* component data
* vuex state 

However, `this.$t()` is not available there.

I have seen people solve this when using vanilla vue-i18n import;

```js
// i18n.js
import Vue from "vue";
import VueI18n from "vue-i18n";

Vue.use(VueI18n);

const messages = {
  en: {
    messages: {
      placeholder: "Placeholder"
    }
  },
  cz: {
    messages: {
      placeholder: "Zástupný symbol :)"
    }
  }
};

export default new VueI18n({
  locale: "en",
  messages
});
```

```js
// some-file.vue
import i18n from "../i18n";

export default {
  name: "HelloWorld",
  props: {
    placeholder: {
      type: String,
      // default: this.$t("value") - Wont work as `this` is not Vue instance
      default: i18n.t("messages.placeholder") // Works
    }
  }
};
```

Is there an equivalent way to do this using the nuxt-i18n module, or do I have to switch to this approach above with the vanilla package?

**Comment by kissu** [comment]
Would like to know too ! ✋🏻

**Comment by rchl** [comment]
You should have access to `$i18n` in vuex state so can do `this.$i18n.t()`.

As for other places that are not based on a Vue-instance then no, there is no built-in way to do that. I think the main reason for that is that it would be a bad practice since even if you would be able to do that, you would have no reactivity so the strings would not update when changing the locale dynamically.

The typical way to handle that would be to pass the locale **key** instead and resolve it to a translation from within the context that handles reactivity.

**Comment by kissu** [comment]
Indeed, `import store from '~/store/index'` is not populated... Would essentially be nice for some exported `vee-validate` error messages.

**Comment by rchl** [comment]
> Indeed, `import store from '~/store/index'` is not populated... Would essentially be nice for some exported `vee-validate` error messages.

I don't know what you mean by that. You are not supposed to import `~/store/index` manually. You are supposed to access it through `$store`.

**Comment by Billybobbonnet** [comment]
I have experienced a bunch of use cases where it would be nice to have this feature.

- From project libs where you store e.g. atomic rules for vuetify forms (https://gist.github.com/Billybobbonnet/64ee0c169220343697dbd159e1713e0c)  (the imports are from a webpack alias)
- From the vuex store getters (afaik it is not possible to use the i18n nuxt flavour helpers in it). I used to truncate text values in there.
- to avoid putting text coming from template data in computed properties + remap it using the i18n keys: I have a few data objects in lib that I import and expose as template data. I wish I could access the i18n instance in them by importing it because it's easier that way. Even if the user changes the language, it goes to another route and re-render the template so no reactivity issue here afaik.

Besides the good/bad practice stance, +1 for this feature. Even if it is not the cleanest approach, it helps to overcome some limitations of Nuxt in corner cases. I think there is a reason why vue-i18n allowed this approach.

**Comment by rchl** [comment]
@Billybobbonnet can you point to some information about vue-i18n allowing this approach? If vue-i18n allows it then this module allows it too. The issue is with initializing vue-i18n with the right options. How do you access those options from your pure module file that has no access to anything Nuxt-related (more specifically the Nuxt Context)?

**Comment by Billybobbonnet** [comment]
@rchl I refer to this topic concerning the ability to expose the i18n instance in the store (including getters): https://forum.vuejs.org/t/how-to-use-t-from-vue-i18n-inside-vuex-action/22146/2

This is similar to what the OP is describing and afaik, nuxt-i18n does not allow it.

**Comment by rchl** [comment]
But you can access `nuxt-i18n` from the store through `this.$i18n`, `this.localePath` etc. All of those are available in Store: getRouteBaseName, localePath, localeRoute, switchLocalePath, $i18n.

Don't understand why anything would be truncated there. Nobody ever reported that AFAIR.

**Comment by rchl** [comment]
And I'll reiterate that I could expose a static function that creates `nuxt-i18n`-extended vue-i18n object but you would still have to provide all the options that you normally provide through module options. So I'm not sure if that would be so useful.

**Comment by Billybobbonnet** [comment]
You can indeed access `nuxt-i18n` in the store actions and mutations. Not in a store getter.

Regarding the feature in question, there could be a misunderstanding (or my assumptions are false):  `nuxt-i18n` creates an instance of `vue-i18n` and inject it into the nuxt context. At this point, it could export it as well as a vanilla object, the same way you could do it if you instantiate `vue-i18n` yourself, directly in your project.

Also (maybe one of my shortcomings again), I don't get why in an i18n nuxt plugin file, where you have this `app.i18n` helper to define hooks, there is no helper methods attached to it (e.g. `$t` or `$tc`). I could have exported it there. When I look at the object, it is already loaded with my locales and, I assume, available for use.

**Comment by rchl** [comment]
> At this point, it could export it as well as a vanilla object, the same way you could do it if you instantiate `vue-i18n` yourself, directly in your project.

No, I don't think you are correct. What you are basically suggesting is storing the created instance in memory, in the nuxt-i18n module. The problem with that is that the instance would be global and shared which would be very hacky and wrong as the instance has to be created per-request so that it's not shared for all requests (some of the nuxt-i18n functionality depends on specific `req` object).

> Also (maybe one of my shortcomings again), I don't get why in an i18n nuxt plugin file, where you have this `app.i18n` helper to define hooks, there is no helper methods attached to it (e.g. `$t` or `$tc`)

`vue-i18n` adds those on the Vue prototype - https://github.com/kazupon/vue-i18n/blob/7609dd3147698557ca81254233663868967af9c6/dist/vue-i18n.common.js#L175-L181 so those are not available directly from the created vue-i18n instance. Or well, the equivalent versions without the `$` character are but those won't use component-local data in case there is some

**Comment by rchl** [comment]
To summarize:
 - you can access relevant API from the Store (including store getters). The issue that @Billybobbonnet had was due to using arrow functions.
 - For any place where you don't have access to `$i18n` or Nuxt context, you need to just pass the translation key and resolve it later.

It's not possible to expose a fully initialized `nuxt-i18n` instance outside of Vue component or Nuxt instance.

**Comment by roselily8** [comment]
Hi @rchl is there an example for scenario 2?

For any place where you don't have access to $i18n or Nuxt context, you need to just pass the translation key and resolve it later.

What the best way to localize vee-validate custom rules in plugin files?

**Comment by rchl** [comment]
I don't know `vee-validate` but maybe you can create a Nuxt plugin from which you would do something like:

```js
import { configure } from 'vee-validate';

export default function({ app }) {
  configure({
    generateMessage: context => {
      return app.i18n.t(context.rule.name);
    },
  });
}
```

I haven't tested it and you would likely also need to extend this logic more but maybe it will work as a start.

reference: https://vee-validate.logaretm.com/v4/guide/i18n
