### ISSUE TITLE
localePath('/career/my-slug') not returning default locales translation

### ISSUE THREAD

**Issue by katerlouis** [nuxt-modules/i18n#1055]
### Version
nuxt-i18n: 6.20.0
nuxt: ^2.12.2

### Nuxt-i18n configuration
    If relevant, please include the configuration you are using for this module.
    For example:
```
export default {
  locales: [
    {
      code: 'de',
      iso: 'de-DE', // https://www.science.co.il/language/Locale-codes.php
      name: 'Deutsch',
      file: 'de-DE.json',
    }, {
      code: 'en',
      iso: 'en-US',
      name: 'English',
      file: 'en-US.json',
    },
  ],

  defaultLocale: 'de',

  // no `~/` necessary – nuxt automatically looks inside folder provided by `srcDir` in `nuxt.config.js`
  langDir: 'locales/',

  // needs to be `true` for language files to work
  lazy: true,

  seo: true,

  vueI18n: {
    // some test messages for nuxt's automatic route generation setup
    // must be in this file and not in locale files
    messages: {
      en: {
        welcome: 'Welcome',
      },
      de: {
        welcome: 'Willkommen',
      },
    },
    fallbackLocale: 'de',
  },
};
```

### Reproduction Link
https://codesandbox.io/s/nuxt-i18n-localepath-test-3d651?file=/pages/career/index.vue

### Steps to reproduce
go to /career and read the template and script snippets

### What is Expected?
`localePath('/career/my-slug')` to return the translated url for my default locale `DE`: `/karriere/my-slug`

### What is actually happening?
It's returning `/career/my-slug`, although the default locale is `DE`

**Comment by rchl** [comment]
`detectBrowserLanguage` option is enabled by default so if your browser is not set to prefer the `de` locale, you might get redirected to English instead.

It should work with `detectBrowserLanguage` set to `false` but note that you might have to remove the `i18n_redirected` cookie because it seems like it will be used even if `detectBrowserLanguage` is `false` (which seems to be a bug).

EDIT: Actually `i18n_redirected` cookie being used even when `detectBrowserLanguage` is `false` doesn't look like a bug since one might want to set locale manually with `setLocaleCookie` even when not detecting locale.

**Comment by katerlouis** [comment]
Hm. But neither do I get redirected to `/en` when I open the page, nor is my browser language english. My browser language is German, so if at all "detect browser language" should reinforce `localePath('/career')` to be `/karriere`, shouldn't it?

plus: lets say you're right and i18n somewhat assumes my locale is `en`, why does `localePath('career')` return the desired `/karriere`.

In any way: the way I understand the docs `localePath('/career')` and `localePath('career')` should return the same value.
But can you confirm this behavior, when you open the sandbox or is it just happening to me?

**Comment by rchl** [comment]
1. That's not what you've asked about but I've noticed that your example using an object parameter to `localePath` uses the wrong route. Should be `career-slug` rather than `career`. You can check the available routes with Vue Dev Tools:
![Screenshot 2021-02-09 at 09 03 57](https://user-images.githubusercontent.com/153197/107333581-f95a4680-6ab5-11eb-96d3-d80775183358.png)

2. As for your main issue, yes it's a bug/missing feature. See #641.

**Comment by rchl** [comment]
According to the point "2" in my previous comment, this should be fixed.
