### ISSUE TITLE
Add typescript type for __i18n

### ISSUE THREAD

**Issue by sugoidesune** [nuxt-modules/i18n#1061]
### Is your feature request related to a problem? Please describe.
I am using mixins with translation-messages and as far as I know those should be put under __i18n key like so:

```js
export default  {
    __i18n: [{
            de: {
                blub: "dog"
            }
    }]
}

```

The problem is I am getting the following error in typescript:
```
 Type '{ __i18n: any[]; }' is not assignable to type 'VueConstructor<Vue> | ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<...>, Record<...>>'.
      Type '{ __i18n: any[]; }' has no properties in common with type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
```

### Describe the solution you'd like
Please add it to the typescript types.

### Describe alternatives you've considered
In the meantime i would love a solution that i could paste into my global types. I have tried the following:

```js
declare module 'vue/types/vue' {

    interface Vue {
        __i18n: Array<Object>;
    }
}

```

### Additional context
I am very new to typescript.

**Comment by rchl** [comment]
I'm not sure where you got the idea that you should put something in `__i18n`. Can you elaborate on that? Maybe you have some links?

Double underscore is typically a convention used to indicate that a property is private so it's not likely that you should be using it in your code.

Maybe explain the problem you are trying to solve because there might exist another way of doing that.

**Comment by rchl** [comment]
I suppose you want to look into `i18n` custom blocks feature: https://kazupon.github.io/vue-i18n/guide/sfc.html#basic-usage ?

You define per-page locales by including an `i18n` block in your page component. That might be internally using the `__i18n` property but you are not really supposed to modify it manually.

`nuxt-i18n` already sets up the `vue-i18n-loader` so it should work out of the box.

**Comment by sugoidesune** [comment]
As mentioned, I have the translations inside mixins,  used in many places in the app. I found this to be the only way to share/import translations. Even if the translations werent in a mixin, but a json, you would still have to merge them into __i18n as far as I understand. Since the standard i18n is reserved and doing anything with it breaks it.

I read about it here, https://github.com/kazupon/vue-i18n/issues/476
and also implemented the custom merge strategy with a minor fix as seen here:

**Comment by sugoidesune** [comment]
I have custom blocks, but they cant be shared between multiple pages and I needed a solution where I can translate something once and use it in multiple places, while still keeping it modular.

**Comment by rchl** [comment]
The [last comment](https://github.com/kazupon/vue-i18n/issues/476#issuecomment-748519437) in the thread you've linked seems to mention a cleaner way to do it.

I won't be adding `__i18n` to types since it's an internal implementation detail of `vue-i18n` so it doesn't really belong in this module (or `vue-i18n` types for that matter).

I think the options here are:
 - use the better solution from the linked issue
 - ask the `vue-i18n` author to add a more straightforward API for achieving the same
 - convince the `vue-i18n` author to add it to its types

That said, you could try something like that to extend the types yourself:

```ts
declare module 'vue/types/vue' {
  interface Vue {
    __i18n: any[]
  }
}
```
