### ISSUE TITLE
Load only the needed translations per page

### ISSUE THREAD

**Issue by fausanchez** [nuxt-modules/i18n#1107]
Hi, i have a huge site with lots of translations.

Im loading the translations from an api using the async function on the locales folder.

I noticed huge size of htmls being served from the server and i found out that Nuxt is putting all my translations on an object "window.NUXT...".

Is there anyway i can get from nuxt-i18n just the translation keys that are being used and load only those from the api? Or any way of loading the translations for the render and not including the the rest of it on the generated HTML?

Thanks

**Comment by fausanchez** [comment]
Does nuxt i18n has something like this this [https://www.i18next.com/principles/namespaces](https://www.i18next.com/principles/namespaces) ?

**Comment by rchl** [comment]
There is no robust and automatic way to only load the used keys because it's technically impossible to automatically figure out what keys are used. The localization key could be constructed in Javascript using concatenation and other weird string transformations or could even come from a database in which case it would be completely hidden from any automatic processor.

That said, some manual way to group your translations should be possible to implement and I'm interested in something like that myself. I'll try to get familiar with the link you've posted and see if it's something that could be added here.

What is currently possible is placing page-specific translations in an `i18n` block in the Vue file (see https://kazupon.github.io/vue-i18n/guide/sfc.html) but that is a manual process and likely not compatible with an approach where you fetch localizations from the API.

The reason this module puts translations in the generated HTML file is that otherwise, the client-side would still have to fetch the translations on load which means an extra network request and more delays. The amount of transferred data would be the same and there would be an overhead of another network request.

EDIT: Well, an argument could be made here that the translation file will be cached by the browser and result in faster page-loads down the road. So there is a balancing act and the results could depend on the circumstances.

**Comment by rchl** [comment]
I'm skeptical whether this is doable but I'll keep it open until I have more time to look into that.

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
