### ISSUE TITLE
localePath uses defaultLocale set in nuxt.config.js and cannot be modified after build

### ISSUE THREAD

**Issue by chanar** [nuxt-modules/i18n#1132]
https://github.com/nuxt-community/i18n-module/blob/52d084d731148af71ec2e9bc91b9b1d8e5eba06f/src/templates/plugin.routing.js#L57

I'm trying to change defaultLocale after build as defaultLocale depends on the domain. As the website is multi-region with multi-language the defaultLocale needs to be set after the build.

Is there currently another workaround I can use?

**Comment by rchl** [comment]
Maybe the code should be changed for the `differentDomains` case but it has to be investigated to check what other implications would it have and whether more code would have to be adjusted.

Also, part of this module's functionality (route generation) can only be done at build-time so that won't be affected by  `defaultLocale` being changed later.

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
