### ISSUE TITLE
default route generated despite using strategy "prefix"

### ISSUE THREAD

**Issue by ehuelsda** [nuxt-modules/i18n#1158]
Am I wrong in assuming that using the strategy "prefix" means that no default route should be generated? I.e. /knowledge should not exist, only /en/knowledge and /de/wissen.

This is my config:
```
  "langDir": "@/locales/",
  "locales": [
    {
      "code": "en",
      "name": "English",
      "iso": "en",
      "file": "en.json",
      "dir": "ltr"
    },
    {
      "code": "de",
      "name": "German",
      "iso": "de",
      "file": "de.json",
      "dir": "ltr"
    }
  ],
  "defaultLocale": "en",
  "lazy": true,
  "strategy": "prefix",
  "vuex": {
    "moduleName": "i18n",
    "syncLocale": true
  },
  "vueI18n": {
    "fallbackLocale": "en"
  },
  "parsePages": false,
  "pages": {
    "knowledge/index": {
      "en": "/knowledge",
      "de": "/wissen"
    },
    "knowledge/_slug": {
      "en": "/knowledge/:slug",
      "de": "/wissen/:slug"
    }
  }
```

**Comment by rchl** [comment]
You are correct with the exception that we still generate an unprefixed fallback when using `nuxt generate` for the purpose of redirecting to the correct prefixed path.

What's the issue exactly?
Create a repro if you have some issue you want me to look at.

**Comment by ehuelsda** [comment]
The issue is that I don't want the non-prefixed path in my sitemap and as long as this path is generated I cannot seem to find a way to prevent it from also being added to my sitemap, despite custom generating my routes in the sitemap module. 

Maybe I'm mistaken in thinking it's an SEO issue to have the non-prefixed route in my sitemap when it is only being used for redirecting to the prefixed route?

**Comment by rchl** [comment]
I understand that we are talking about a statically generated (`nuxt generate`) site because only then will the fallback be generated?

I might just remove that fallback because the proper way to handle fallback is to configure hosting to use the nuxt-generated 200.html file instead.

@divine any opinions? I think I've added this fallback after discussing it with you?

**Comment by ehuelsda** [comment]
You are right, it is a statically generated site. Sorry, I forgot to mention that.

**Comment by rchl** [comment]
BTW, if you have SEO enabled then those routes include a `canonical` tag so from the SEO perspective it shouldn't be an issue.

BTW2. How is your hosting configured? Does it return a fallback HTML for non-existing routes and if so, does it return 200 or 404 status code for those?

**Comment by divine** [comment]
> I understand that we are talking about a statically generated (`nuxt generate`) site because only then will the fallback be generated?
> 
> I might just remove that fallback because the proper way to handle fallback is to configure hosting to use the nuxt-generated 200.html file instead.
> 
> @divine any opinions? I think I've added this fallback after discussing it with you?

Hello,

Exactly, the issue that you kindly fixed was it didn't render any content at all and redirect happened after full page load which is weird because that page was empty.

Removing that fallback will only harm, yeah, having a pre-rendered (fallback) page with canonical links generated via this plugin is much better and this is what search engines prefer.

I'm not talking about some articles only but experience with nuxt site (about 150k clicks/month), search engines selected on its own canonical page which was simply empty page in search results, people clicking on it would then redirect, so basically double redirect.

Actually, last year there were a lot of new features added (canonical, alternate, fallback) which simply fixed all SEO issues and there is simply zero harm was with all these changes.

I'm not really sure, why somebody wouldn't like the fallback page in a static environment because you aren't able to redirect except after full page load via JavaScript?

Thanks!

**Comment by divine** [comment]
> I might just remove that fallback because the proper way to handle fallback is to configure hosting to use the nuxt-generated 200.html file instead.

Oh, I just remembered it, there were two similar issues, that one we're talking is https://github.com/nuxt-community/i18n-module/issues/805 .

The issue was that in a static environment without having a fallback page it was returning a 404 error code even on main page and then a redirection happens.

I'm not sure how you'd configure that redirection to a fallback page without the 404 error code?

Hosting services returns a 404 error code even if you fix that in configuration on Netlify/Pages/Vercel and etc the error is shown on nuxt because that page doesn't exist:

```
This page could not be found
Back to the home page

Nuxt.js
```

Thanks!

**Comment by ehuelsda** [comment]
@rchl I'm using the $nuxtI18nHead method in my layout with addSeoAttributes. 

My site returns 404 status code on non-existing routes. That is however still a changeable strategy as the site is not launched yet. 

I see you are right about the canonical being added, so I'll accept the extra links in my sitemap as I don't want to spend too much time on this atm.

Anyway, thank you for the quick feedback.

**Comment by rchl** [comment]
So in statically generated pages, you have either an issue with blank page rendering and then redirecting to the correct page or a page rendering in another language and then redirecting to the correct locale. So it's not ideal either way.

I'll close this as it's not really fixable.

**Comment by divine** [comment]
> So in statically generated pages, you have either an issue with blank page rendering and then redirecting to the correct page or a page rendering in another language and then redirecting to the correct locale. So it's not ideal either way.
> 
> I'll close this as it's not really fixable.

Hello,

I think nuxt nitro might resolve such issues and this will be a mix of server/static rendering but not a static version on its own.

Thanks!
