### ISSUE TITLE
Why `asyncData is executing twice` after calling `switchLocalePath`?

### ISSUE THREAD

**Issue by d4rkr3pt0r** [nuxt-modules/i18n#1160]
Here is my `nuxt.config.js`
```
export default {
  head: {
    title: 'Test',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },
  i18n: {
	locales: [
		{
		  code: 'en',
		  name: 'English'
		},
		{
		  code: 'es',
		  name: 'Español'
		},
		{
		  code: 'fr',
		  name: 'Français'
		}
	  ],
    defaultLocale: 'en',
    vueI18n: {
      fallbackLocale: 'en',
      messages: {
        en: {
          welcome: 'Welcome'
        },
        fr: {
          welcome: 'Bienvenue'
        },
        es: {
          welcome: 'Bienvenido'
        }
      }
    }
  },
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
	'nuxt-i18n'
  ],
}
```
And here is my index.vue : 
```
<template>
  <div class="container">
    <nuxt-link v-for="locale in availableLocales" :key="locale.code" :to="switchLocalePath(locale.code)">
      {{ locale.name }}</nuxt-link>
    {{ $t('welcome') }}
  </div>
</template>
<script>
  export default {
    asyncData({ app }) {
      return app.$axios.$get(`https://reqres.in/api/users/2?timestamp=${new Date().getTime()}`)
        .then((res) => {
          return {
            data: res
          }
        })
    },
    computed: {
      availableLocales() {
        return this.$i18n.locales.filter(i => i.code !== this.$i18n.locale)
      }
    }
  }
</script>
<style>
  .container {
    margin: 0 auto;
    min-height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    text-align: center;
  }
  a {
    padding: 0 15px;
  }
</style>
```
Sanbox : [https://codesandbox.io/s/nuxt-i18n-forked-efgyo](https://codesandbox.io/s/nuxt-i18n-forked-efgyo)
The problem is that get request is sending twice one every `switchLocalePath` call. I might be doing something wrong somewhere.Can anyone help?

**Comment by rchl** [comment]
That looks weird indeed. Need to look closer when I have more time.

BTW. All `switchLocalePath` does is it returns a string with the path of the route for the given locale.

**Comment by rchl** [comment]
Well, I know what's happening but I'm not sure what to do about it.

`vue-i18n` calls `VueComponent.$forceUpdate()` on locale change: https://github.com/kazupon/vue-i18n/blob/13f3e618d5a7c3c32fe99f156d1ee2b4e199a5a4/src/index.js#L250-L259

And, only in dev mode, Nuxt implements/overrides `$forceUpdate` on the page component to trigger, amongst others, an `asyncData` call: https://github.com/nuxt/nuxt.js/blob/8e2cad5a8fd7c4fa731fea92d762b650ee5ce095/packages/vue-app/template/client.js#L740-L746

This is only a problem during development since it's related to "hot reload" which is not enabled otherwise.

Not sure who should do something here...

**Comment by rchl** [comment]
I've reported https://github.com/nuxt/nuxt.js/issues/9209

**Comment by rchl** [comment]
I've checked the referenced Nuxt bug recently with latest dependencies and it seems to be resolved.
