### ISSUE TITLE
Support session cookie for storing locale

### ISSUE THREAD

**Issue by pkpowell** [nuxt-modules/i18n#1203]
Is it possible to save the language selection somewhere else eg in the vuex store? We're trying to go cookieless - or is a cookie like this exempt from GDPR?

**Comment by rchl** [comment]
As far as GDPR you'd have to search for advice on that somewhere else. If you find some concrete information, I'd also be interested to know. :)

Storing in vuex store is not possible since vuex store is not really storing anything persistently. It is created per-request and needs to get the source information from somewhere like cookie (localStorage wouldn't work since that's client-only).

I guess an option would be to not allow persisting the locale until the user consents to cookies but then, to still allow user to change locale, there would need to be some fallback like passing the locale through the URL. That sounds messy though.

**Comment by pkpowell** [comment]
Thanks for the quick reply. I'll keep an eye open for any gdpr info.
What I need is for the locale choice to last for the session, not longer. 
If I set `useCookie: false` I can still switch locales but it reverts back to the default locale on route change. Is there a way to prevent this? 
I popped in a middleware to set the locale on route change which works, but it always switches back first.

**Comment by rchl** [comment]
There could be an option to create a session cookie but there isn't right now.

**Comment by rchl** [comment]
I'll close this because having researched GDPR a bit more now, a cookie like the locale cookie can be considered an "essential" cookie and thus can be set before the consent is given.
