### ISSUE TITLE
Prefix exception for some routes

### ISSUE THREAD

**Issue by dannycoulombe** [nuxt-modules/i18n#1222]
Hello Nuxt community!

We are working on a multilingual blog where our users are creating content in one language but visible in many languages (main post stays in post's language).

We support five languages across the site and our user can access our pages (those our admins creates) in all five languages. So the "prefix" strategy works fine for us 95% of the time.

But ```User A``` can create post in ```language X``` and ```User B``` can create post in ```language Y```, but we do not want to prefix these posts, since they are only available in one language. We instead want to make them available from ```/post/slug``` without prefix so we don't create duplicatas that search engines could detect.

So our question is, how can we add an exception to the ```prefix``` strategy, so one specific route can behave differently than all others. We try adding in-component configurations, but it doesn't seem to work.

nuxt.config.js
```
i18n: {
	seo: true,
	strategy: 'prefix',
	langDir: '~/locales',
	lazy: true,
	locales: [
		{ code: 'fr', iso: 'fr-FR', file: 'fr-FR.json', name: 'Français', },
		{ code: 'es', iso: 'es-ES', file: 'es-ES.json', name: 'Español', },
		{ code: 'it', iso: 'it-IT', file: 'it-IT.json', name: 'Italiano', },
		{ code: 'pt', iso: 'pt-PT', file: 'pt-PT.json', name: 'Português', },
		{ code: 'en', iso: 'en-US', file: 'en-US.json', name: 'English', }, // DEFAULT LANGUAGE ALWAYS LAST!
	],
	defaultLocale: 'en',
	detectBrowserLanguage: {
		onlyOnRoot: true,
	},
	parsePages: true,
},
```

/pages/post/_slug
```
export default {
	nuxtI18n: false,
}
```

**Comment by rchl** [comment]
But `/pages/post/_slug` route is used for all posts right? So disabling nuxt-i18n for that route would disable it for all posts so that doesn't seem like the way to go.

Which routes get a prefix or not is defined at build time so I don't think that this is very compatible with your use case where you have dynamically created posts. There is no way to customize that per-route dynamically at run-time.

So no, I don't think this can be done right now.
