### ISSUE TITLE
Can I disable canonical links on specific pages?

### ISSUE THREAD

**Issue by zangab** [nuxt-modules/i18n#1297]
Hi,
I do have a top-level catch-all page meaning `pages/_.vue` that is used to build all kind of (sub-) pages via data from my API. My static generated site also supports multiple locales (f.e. english, french, german). I use the `$nuxtI18nHead({ addSeoAttributes: true })` function in my base `layout` to inject / update canonical links on all pages. However, for my use-case, I do not want this behavior on my `_.vue` page because the generated canonical links are wrong.

So for example, these links should reference each other, but have completely different urls. I have the correct API data to handle that but I need to disable / override those links. How can I do that?
- EN: `.../en/premier-league/leicester`
- FR: `.../fr/ligue-1/psg`
- DE: `.../de/bundesliga/dortmund`

Looking forward to hear from you.
Thx. Br, Gabo

**Comment by benwalsh** [comment]
I have been tearing my hair out with this because I want to modify the canonical link on **AMP** pages. Being able to disable it (and then add my own custom one) would work just as well, if I could do that.

If my URL is `https://www.mydomain.com/articles/some-article/amp/`, then I would like the link to be `<link rel="canonical" href="https://www.mydomain.com/articles/some-article/" />`. There are a couple of things that I feel should work:

1. Adding a `link` with the `hid="i18n-can"` attribute so that it overwrites the existing link instead of appending to the list.
2. Modifying the object returned by `this.$nuxtI18nHead` to replace the `link` array with the modified version.

Neither is doing it -- the `i18n` tags are always added last, overwriting is done in the `head ()` method of the component or in `nuxt.config.js`.

**Comment by zangab** [comment]
@benwalsh 
well, I could do a ugly quickfix by disabling it and push my own canonical links.
basically, I just added another layout that removes the default links like
```js
  head() {
    const seoMetaHeaders = this.$nuxtI18nHead({ addSeoAttributes: true })
    delete seoMetaHeaders.link // remove canonicals because these are handled manually

    return seoMetaHeaders
  }
  ```
  
as this is all I do in the layout, it's working fine so far, but, well, kinda ugly.
in the respective pages, I add my canonicals based on the API data.

**Comment by benwalsh** [comment]
That does solve the problem, thank you!

**Comment by tonqa** [comment]
In the head section of nuxt config I filtered out the canonical links.
```javascript
const i18nHead = this.$nuxtI18nHead({ addSeoAttributes: true });
i18nHead.link = i18nHead.link.filter((e) => e.rel !== "canonical");
```
