### ISSUE TITLE
aliases with i18n support

### ISSUE THREAD

**Issue by rickthepick** [nuxt-modules/i18n#1298]
hello.  how do i do this using i18n?
(feature from https://github.com/nuxt-community/router-extras-module)
```
<router>
 {
    path: '/posts',
    alias: [
      '/articles',
      '/blog'
    ]
 }
</router>
```

i want to be able to configure their i18n routes:
```
  "posts": {
     pt: "/posts-pt"
     ...
  },
  "articles": {
    pt: "/articles-pt"
    ...
  },
  "blog": {
    pt: "/blog-pt"
    ...
  },
```

**Comment by rchl** [comment]
There is https://i18n.nuxtjs.org/routing#custom-paths

**Comment by rickthepick** [comment]
Thanks.  This is different because aliases allow several different names for the same page.

Aliases are actually generated using i18n, but you don't have any control over them.  For example, if the page 'main.vue' contains:
```
<router>
 {
    path: '/posts',
    alias: [
      '/articles',
      '/blog'
    ]
 }
</router>
```
then /posts, /articles, /blog will all be generated with the main.vue page content, but unfortunately you do not have control over i18n, e.g.,
```
  "blog": {
    pt: "/blog-pt"
    ...
  },
```
is ignored even though /blog is generated for all the locales.

**Comment by rickthepick** [comment]
What I really need is this:
```
"blog": {
  en: "/blog",
  pt: false,
  ko: false
}

**Comment by hacknug** [comment]
I think my proposed change in #1281 would allow for such functionality. I'm using it in production for a couple sites I needed to be able to define the routes manually since the module didn't knew how to handle those cases.

We would need to make sure my changes don't break core functionality (pretty sure I didn't account for all scenarios this module handles) but I wanna say it wouldn't be too hard to also add support for this?

**Comment by hacknug** [comment]
not stale
