### ISSUE TITLE
setRouteParams should also control if the route is valid or not

### ISSUE THREAD

**Issue by yakovyarmo** [nuxt-modules/i18n#1366]
Hi,
We are in a situation where some of our pages are translated and some are not.
It would really help if there was a way to disable the route using setRouteParams.

**Comment by rchl** [comment]
I think it makes sense to call `context.error` in this case, without using `setRouteParams`.

**Comment by BirknerAlex** [comment]
I would also love to see this feature. Currently, I am fetching the content in setup() (GraphQL) which returns a list in which locales the content is available, the route slugs are dynamic for each locale too.

Example
```/en/blog/:slug```

The current behaviour is that non translated pages are still showing the the alternative links in `<head>` and locales on the locale selector, which results in 404 because the slugs are wrong for non-existing languages.

Disabling it with https://i18n.nuxtjs.org/ignoring-localized-routes is not working since the decision if that specific entry  is available or not happens during the rendering and not on a per page component basis. 

Something like the following would really help with solving this:
 ```javascript
    await $store.dispatch('i18n/setRouteParams', {
      de: { slug: 'eintrag123' },
      en: { slug: 'entry123' },
      ja: false,
    });
```

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
