### ISSUE TITLE
Can I dynamically switch between different 'defaultlocales' according to different URLs  ？

### ISSUE THREAD

**Issue by lijx2018github** [nuxt-modules/i18n#1391]
like this 

![997F54F2-ADCD-4b0f-8D17-1AB0E4D4A116](https://user-images.githubusercontent.com/45417524/153117263-f8b8fa85-6345-4f10-b020-4310bc5206c4.png)

**Comment by emielmolenaar** [comment]
This would be a nice feature.

**Comment by BobbieGoede** [comment]
Not sure if there is still demand for this feature, but I'm very slowly working through all the issues.

Besides `defaultLocale` being used in the build step (so changing it at runtime is currently not possible), what is the use case for changing it based on URL?

**Comment by randyhoulahan** [comment]
My use case is one head on a cms too embarrassed to name.  Upto 200 sites per head having different default and locals.

**Comment by randyhoulahan** [comment]
Its done?  https://i18n.nuxtjs.org/docs/options/runtime-config

**Comment by gaetansenn** [comment]
Hi,

I have a situation that requires me to update the defaultLocale based on the domain name.

My website uses different domain names depending on the country:

If I visit mydomain.fr, it takes me to the French website where I can ship to France.
If I visit mydomain.es, it takes me to the Spanish website where I can ship to Spain.
If I visit mydomain.it, it takes me to the Italian website where I can ship to Italy.
The challenge is that I'm using the same Nuxt server instance for all these domains, and on each domain, users can switch between all available locales.

The only difference is that I need to set a different defaultLocale depending on the domain name.

Is there a way to handle this? Since the runtime environment won't help in this case, an appropriate solution would be to update the defaultLocale during the hook or plugin phase, based on the domain name obtained from useRequestURL().hostname, for instance.

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!

The feature requested sounds similar to https://i18n.nuxtjs.org/docs/guide/multi-domain-locales, maybe it suits your use case?

**Comment by gaetansenn** [comment]
Hi @BobbieGoede,

I apologize for the confusion. This is actually the case with the latest version (v8) of Vue i18n. Unfortunately, the multi-domain-locales feature doesn’t fit my scenario, as it handles locale based on domains. In my case, all locales are available across domains, but I need to set a different default locale depending on the domain.

Is there a way to dynamically inject the defaultLocale value at runtime, rather than at build time, since it needs to adapt based on the domain name?

**Comment by BobbieGoede** [comment]
@gaetansenn 
Unfortunately we don't support this (yet), we're discussing/tracking this in https://github.com/nuxt-modules/i18n/issues/2289 for v8 and higher.

**Comment by gaetansenn** [comment]
@BobbieGoede 
Yes I'm already watching this issue thank you for your reply
