### ISSUE TITLE
How to get current locale in nuxt generate

### ISSUE THREAD

**Issue by ZanWolf** [nuxt-modules/i18n#1423]
I am having some problems while generating dynamic routes for Nuxtjs. 
I have a list of products that I retrieve from the API and I am generating single pages for them.

Everything works flawlessly for the default locale (I am using Nuxt i18n).

The problem is, that I want to call different API if in another locale. 
I have tried many things to get **current locale into routes()** method but without any luck.

``` 

generate: {
    target: "static",
    crawler: true,

    routes: function () {

    /* I WANT TO GET CURRENT LOCALE HERE FROM i18n
    so that I can call the correct API endpoint */

      let products = axios.get('https://example.com/v1/get-products').then((res) => {
        return res.data.map(product => {
          return {
            route: '/product/' + product.slug,
            name: 'product',
            payload: product
          }
        })
      })
      return Promise.all([products]).then(values => {
        return [...values[0]]
      })
      
    }
  }```


Is there any way to get the current locale while generating the routes ?

**Comment by rchl** [comment]
Can't you make multiple calls for all locales that you support and return concatenated routes for all of them?

At the point of calling this hook, Nuxt doesn't know the "current locale" because it isn't generating any specific route.

**Comment by ZanWolf** [comment]
@rchl thank you for your answer, but I am a little bit confused about what "concatenated" routes mean. I can make multiple calls for all locales, but I don't know how to tell the Nuxt in which locale they are.

**Comment by kissu** [comment]
If you generate all the routes ahead of time, you don't need to think about the routes needed for the end user. That is because he will arrive on the proper route by itself.

As an example, let's say that you generate 🇫🇷, 🏴󠁧󠁢󠁥󠁮󠁧󠁿 and 🇪🇸 routes because you don't know which one the end user will be using. You get all of those 3 ahead of time. Then, the user arrives on your webapp. Looking at his current [browser language](https://i18n.nuxtjs.org/browser-language-detection/), he will arrive on the proper locale. 👍🏼

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
