### ISSUE TITLE
[NEXT] useLocalePath() not working in middleware

### ISSUE THREAD

**Issue by szulcus** [nuxt-modules/i18n#1605]
Continued issue #1542 

### Version
@nuxtjs/i18n: 8.0.0-beta.3
nuxt: 3.0.0-rc.12

### Nuxt configuration

Please change to `[x]` if relevant for this issue:

 - [x] Applies to a site deployed to a static server (site generated with `nuxt generate`)
 - [  ] Applies to a site deployed to a server with a Node backend

### Reproduction Link
I don't have time to create another project. Just paste this code into any .vue file in the pages folder:
```ts
const localePath = useLocalePath();
definePageMeta({
	middleware() {
		navigateTo(localePath('index'));
	},
});
```

### Steps to reproduce
Answer above.

### What is Expected?
Working `localePath` function.

### What is actually happening?
`localePath` is undefined.

**Comment by kazupon** [comment]
Thank you for your feedback always!

`useLocalePath` is a composable functions. Normal composable functions must be executed in the context of a Vue `<script setup>` or `setup` hook.

Since the `definePageMeta` middleware is not a Vue setup context, so composable functions defined in general Vue will not work. However, you would realize the composable funcctions provided by nuxt, such as `useNuxtApp`, `useRouter` and more will work. Why do they work? It's because nuxt uses [`unctx`](https://github.com/unjs/unctx) to implement (wrap) them in a way that works well.

So, make them work correctly, we need to implement the composable fucntions provided by @nuxtjs/i18n, including the `useLocalePath`, in the same way as the composable functions in nuxt.

As the workaround, you can use the API prefixed with `$` exported by `NuxtApp` as follows:

```ts
definePageMeta({
	middleware() {
        const { $localePath } = useNuxtApp();
		navigateTo($localePath('index'));
	},
});
```

**Comment by szulcus** [comment]
@kazupon I understand. `$localePath` works, unfortunately the problem is that its type requires `NuxtApp` as the first argument. Can it be fixed?
In `/node_modules/@nuxtjs/i18n/dist/runtime/plugin.d.ts`:
![image](https://user-images.githubusercontent.com/48328739/199755536-3e4a496d-4c1a-469e-8e72-9c4b7ee8e1c0.png)
