### ISSUE TITLE
Error: Invalid linked format whenever `@` is included

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt-modules/i18n#1618]
### Version
@nuxtjs/i18n: 8.0.0-beta.3
nuxt: 3.0.0-rc.13

### @nuxtjs/i18n configuration
```
i18n: {
    locales: ["en"],
    defaultLocale: "en"
}
```

### Reproduction Link
Will provide if needed.

### Steps to reproduce
Create a per-component translation block with any key and value containing an `@` sign, as shown on the screenshot.

### What is Expected?
An email address to be a valid value in the below scenario:
```
<i18n lang="json">
{
    "en": {
        "contactInfoSections": {
            "askForOfferSection": {
                "emailAddress": "test@abc.com"
            }
        }
    }
}
</i18n>
```

### What is actually happening?
![image](https://user-images.githubusercontent.com/48835293/200333796-8004dd80-f32c-4900-8311-3be368940d4c.png)

**Comment by kazupon** [comment]
Thank you for your reporting!

`@` character and several characters has been special character from vue-i18n v9.x, because these is used in message syntax as special literal in message-compiler 
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters

You can avoid with using literal interpolation
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#interpolations

Thanks for using nuxtjs/i18n!
