### ISSUE TITLE
localePath returning wrong url when using SSG and multiple JSON files

### ISSUE THREAD

**Issue by StefanVDWeide** [nuxt-modules/i18n#1810]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.6.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `app`, `runtimeConfig`, `modules`, `content`, `css`, `build`, `i18n`, `sitemap`
- Runtime Modules:  `@nuxt/content@2.3.0`, `@nuxtjs/i18n@8.0.0-beta.8`, `@nuxt/image-edge@1.0.0-27840416.dc1ed65`, `@nuxtjs/tailwindcss@6.2.0`, `@funken-studio/sitemap-nuxt-3@4.0.4`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-npjsrd?file=pages/blog/index.vue

### Describe the bug

When using SSG in combination with lazy loading languages and nuxt/content, the localePath function will always return the URL for the default locale even if a different language is selected. 

So for example, my `/blog` page retrieves a number of posts and has to change the URLs to the individual posts based on the current locale. I'm using the `prefix_except_default` strategy so what should happen is:

```
// nothing in the URL since NL is the default locale
example.com/blog/post-1

// en in the URL since we have switched
example.com/en/blog/post-1
```

What is actually happening
```
// nothing in the URL since NL is the default locale
example.com/blog/post-1

// nl even though we have switched to the en locale
example.com/nl/blog/post-1
```

This only seems to be an issue when using SSG. running `npm run dev` it works correctly.

**Comment by StefanoTesla** [comment]
Same problem in #1804 I didn't take a look about this, with last beta (updated today morning) SSG is "totally" broken see #1812
@kazupon 
I hope my messages will se as a "bug trace help" and not like disappointment 👍🏻 unfortunatly I don't know javascript to give a hand

**Comment by janvennemann** [comment]
I think this is not only related to SSG, localization in SSR is also broken in the latest `8.0.0-beta.8`. Everything was working fine on `8.0.0-beta.7`, but we updated since we wanted to try the `files` option. Reverting back to `8.0.0-beta.7` and `file` option resolved the issue for now. 

[Here](https://codesandbox.io/p/sandbox/little-meadow-fzuxnr?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A5%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A5%2C%22startLineNumber%22%3A9%7D%5D) is a CodeSandbox with a minimal reproduction example. Notice how the text flickers from `hello` to `Hello World` as the translation is only loaded on the client. Downgrading to `beta.7` solves the issue.

**Comment by kazupon** [comment]
@janvennemann 
Hi!
Thank you for your feedback!

Your repro repo is not an SSG issue, but a regression issue with lazy loading enhanced in beta.8. Could you please open as a new issue? 🙏

**Comment by kazupon** [comment]
@janvennemann 
You issue is same as #1812, so yon don’t need to open a new issue. 👌

**Comment by kazupon** [comment]
I've found out degrade with https://github.com/nuxt-modules/i18n/pull/1733
