### ISSUE TITLE
SSG freezed the browser 

### ISSUE THREAD

**Issue by StefanoTesla** [nuxt-modules/i18n#1851]
### Environment
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@9.4.2`
- Builder:          `vite`
- User Config:      `pages`, `css`, `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9-27926914.891e694`
- Build Modules:    `-`
------------------------------

### Reproduction

test.stefanotesla.it

### Describe the bug

Sorry for short implementation I'm from Mobile and the Project is At the office

I have problems with SSG, once i load the site and visit it the browser freez.

I tried with Chrome and a Virgin installati on of Firefox

All details and reproduction here:

https://github.com/nuxt/nuxt/issues/18876

I asked to the nuxt team bit they think is related to i18n

**Comment by kazupon** [comment]
Thank you for your reporting!

Hmm, This is an interesting issue. 😅 
I have found out this issue that has been occurring since this modification.
https://github.com/nuxt-modules/i18n/pull/1842/

As I commented at the PR, I was using incorrect `navigateTo` in the i18n module, so I was fixed it.
That updating seems to affect the logic somewhere in routing.
