### ISSUE TITLE
Rename `i18n:extend-messages` to `i18n:extendMessages`

### ISSUE THREAD

**Issue by kazupon** [nuxt-modules/i18n#1942]
In that case, should I rename the existing `i18n:extend-messages` hook to be camel case as well?

_Originally posted by @ineshbose in https://github.com/nuxt-modules/i18n/pull/1919#discussion_r1133077515_

**Comment by ineshbose** [comment]
Brilliant issue to get contributing to this repo! 😄

**Comment by kazupon** [comment]
We might be able to deplicate i18n:extend-message. Because I think we can do the same thing with the recently supported Layers. /cc @BobbieGoede

https://v8.i18n.nuxtjs.org/guide/layers

The reason for deprecated is that this hook pre-compiles the messages passed by vue-i18n at build-time, and generates code in i18n.options.mjs in the template.
This is javascript to javascript and not safe.
Also, if large messages are set in this hook, i18n.options.mjs will become large, resulting in a performance issue.

reference discord link:
https://discord.com/channels/1044887051155292200/1063952424764719154/1064230457098645645

**Comment by BobbieGoede** [comment]
@kazupon that should be possible, I can look into adapting for modules. Are there any advantages over extending messages with objects instead of files with the current approach?

Is there a preferred way of registering/discovering modules that want to provide messages/locales? Using a hook I figure it could work something like this for modules:
```ts

export default defineNuxtModule({
  async setup(options, nuxt) {

    // could potentially be simplified inside a function to handle resolve and hook
    const resolver = createResolver(import.meta.url)
    nuxt.hook('i18n:registerModule', registerI18nModule => {
      registerI18nModule({
        // paths may be more unpredictable compared to layers?
        langDir: resolver.resolve('./locales'),
        locales: [
          {
            code: 'en',
            iso: 'en-US',
            file: 'en.json',
            name: 'English'
          },
          {
            code: 'nl',
            iso: 'nl-NL',
            file: 'nl.json',
            name: 'Nederlands'
          }
       ]
    })
  }
)
```

I'm not sure if `iso` and `name` are relevant for adding messages from modules.

The discord link doesn't work for me so I am not sure what it references 😅
