### ISSUE TITLE
when use array type module configuraion, i18n-t tag and pluralisation don't work on production build

### ISSUE THREAD

**Issue by gbyesiltas** [nuxt-modules/i18n#2089]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.5.0`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `ssr`, `components`, `runtimeConfig`, `modules`, `app`, `css`, `postcss`, `vite`
- Runtime Modules:  `nuxt-vitest@0.7.0`, `@nuxt-alt/auth@2.5.0`, `@pinia/nuxt@0.4.9`, `nuxt-icon@0.4.0`, `@vueuse/nuxt@9.13.0`, `@formkit/nuxt@0.17.0`, `@nuxtjs/i18n@8.0.0-beta.11`, `@nuxt/image-edge@1.0.0-28020728.5df24eb`, `@nuxtjs/robots@3.0.0`
- Build Modules:    `-`

### Reproduction

Here's a stackblitz reproduction with only this module as a dependency: https://stackblitz.com/edit/github-mqaaqa-zzgq5f?file=app.vue

### Describe the bug

Translations that include pluralisations and translations via the `i18n-t` tag do not work when the application is built using `npm run build` and `npm run preview` whereas they do work on the development build.

**Comment by JasonLandbridge** [comment]
Same issue here, this is blocking deployment unfortunately. I am on exactly the same environment as @gbyesiltas

**Comment by Xezard** [comment]
![image](https://github.com/nuxt-modules/i18n/assets/17483454/0e594cdc-5b34-47e0-b741-dbe9afe283bd)

I confirm that the bug is relevant for the following configuration: 
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge",
"nuxt": "3.5.0"

The bug seriously blocks the release of the project in production(

UPD 21.05.2023: the replacement of variables in translations also does not work with the production build:
![image](https://github.com/nuxt-modules/i18n/assets/17483454/d5a7243e-1bd7-4edb-925d-c1e080adaf7b)
along with this, the following error periodically appears in the server console: `[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format.`

**Comment by kazupon** [comment]
simillar issue #1909 

I found out reproduction pattern.

This issue seems to occur when the module in nuxt.config.ts is configured as an array.
It works correctly when the nuxt i18n module is configured in the commonly used object format.

```ts
import i18nConfig from './nuxt.i18n.config';

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  // NOTE: not work
  // modules: [['@nuxtjs/i18n', i18nConfig]],

  // NOTE: work correctly
  modules: ['@nuxtjs/i18n'],
  i18n: i18nConfig
});
```

**Comment by gbyesiltas** [comment]
> simillar issue #1909
> 
> I found out reproduction pattern.
> 
> This issue seems to occur when the module in nuxt.config.ts is configured as an array. It works correctly when the nuxt i18n module is configured in the commonly used object format.
> 
> ```ts
> import i18nConfig from './nuxt.i18n.config';
> 
> // https://v3.nuxtjs.org/api/configuration/nuxt.config
> export default defineNuxtConfig({
>   // NOTE: not work
>   // modules: [['@nuxtjs/i18n', i18nConfig]],
> 
>   // NOTE: work correctly
>   modules: ['@nuxtjs/i18n'],
>   i18n: i18nConfig
> });
> ```

Yep, this fixes the issue indeed. Thanks! :)
