### ISSUE TITLE
Using component interpolation, break production build

### ISSUE THREAD

**Issue by gbendjaf** [nuxt-modules/i18n#2104]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@9.5.0
- Builder:          vite
- User Config:      devServer, modules, vite, css
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11, @pinia/nuxt@0.4.9, @nuxt/image-edge@1.0.0-28059208.2abef1b
- Build Modules:    -

### Reproduction

I don't really know how to give a reproduction link, since it seems to be linked to Vercel in some way.
Let me know if giving the prod url would help.

### Describe the bug

So I'm using component interpolation without any problem in dev mode, everything work as expected, here is my code:

```
<i18n-t
  :keypath="`homePage.easy-to-use.list-${index}.text`"
  tag="p"
  scope="global"
>
  <template v-slot:bold1>
    <b>{{ $t(`homePage.easy-to-use.list-${index}.bold-1`) }}</b>
  </template>
  <template v-slot:bold2>
    <b>{{ $t(`homePage.easy-to-use.list-${index}.bold-2`) }}</b>
  </template>
</i18n-t>
```

When deploying my project with this, I got an error 500 on my build.

I got no error on Vercel side during building, it's only when accessing the URL that I got the error, nothing in the console except the error 500 in itself.

If I comment this specific part, everything is back to normal, so component interpolation is breaking my prod build but i can't figure out why.

### Additional context

![image](https://github.com/nuxt-modules/i18n/assets/58231371/ddba7665-ebdb-4246-a0e1-bda98abac1db)

### Logs

```shell
I attached an image of the log of the project, I hope it can help.
```

**Comment by kazupon** [comment]
Thank you for your reporting!

First, Could you try to use edge channel version?

I greatly appreciate your report but would appreciate a repo with minimal reproduction code.
And you seem to be having this problem with Vercel, please give us more information around Vercel environments 🙏 
I don't know much about Vercel as I don't use it often 😅

**Comment by sultondev** [comment]
Hi @gbendjaf 

Vercel shows the deployment was successful but when you enter the website you're getting 500 error like this:

<img width="633" alt="244109504-cec5ab39-1cdf-4a64-ab3e-af10d11d8789" src="https://github.com/nuxt-modules/i18n/assets/74731394/835e638a-349c-4be6-ad35-7820cc216ec3">

If I understood your issue correctly. I was getting the same error because of yarn.lock file in vercel. Here is the way to solve this issue. 

1. Add your yarn.lock file into .gitignore 
2. do some change and commit it
3. git push 

link to nuxt vercel builder: https://github.com/nuxt/vercel-builder/issues/806

**Comment by kazupon** [comment]
Close in-activity.
If you have still the issue, please you will open new issue.

Thanks!
