### ISSUE TITLE
vueI18nLoader not working in V8

### ISSUE THREAD

**Issue by notflip** [nuxt-modules/i18n#2137]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.19.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@8.19.3
- Builder:          vite
- User Config:      runtimeConfig, app, css, modules, postcss, devtools
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

```
<template>
  <div>
    {{ $t('hello') }}</h1>
  </div>
</template>

<i18n lang="yaml">
nl:
  hello: Hello
fr:
  hello: Bonjour
</i18n>
```

nuxt.config.ts
```
    modules: [
        ['@nuxtjs/i18n', {
            baseUrl: process.env.NUXT_PUBLIC_SITE_URL || 'http://localhost:3000',
            strategy: 'prefix_except_default',
            defaultLocale: 'nl',
            locales: [
                { code: 'nl', iso: 'nl', file: 'nl.ts' },
                { code: 'fr', iso: 'fr', file: 'fr.ts' },
            ],
            langDir: 'lang/',
            vueI18nLoader: true
        }]
    ],
```

### Describe the bug

I'm getting the error
`[intlify] Not found 'hello' key in 'nl' locale messages.`

When trying to use the `vueI18nLoader` option, as seen in the docs here
https://i18n.nuxtjs.org/per-component-translations

**Comment by kazupon** [comment]
The `vueI18nLoader` option is no longer required, because i18n custom blocks are now supported by default in v8.
see the docs:
https://v8.i18n.nuxtjs.org/guide/migrating#deprecated-vuei18nloader-option

when you will use i18n custom block, you need `const { t } = useI18n({ inheritLocale: true })` on script setup.
`$t` support global scope only for Composition API (script setup)

Thanks!

**Comment by notflip** [comment]
Thanks @kazupon , what's the difference between `$t` and `t`?

**Comment by andamansunda** [comment]
Hey, I am really thankful for this module, so please excuse me if I sound ungrateful. But I just spent 4 hours trying to figure out how to get the same problem solved as notflip. The problem is that there are a number of tutorials out there showing that we should use vueI18Loader, and then there is a small note towards the bottom of the migration guide, which does share the info about i18n custom blocks are now supported by default. But the missing piece of the puzzle, what seems to be completely undocumented, is found in the issues here.
