### ISSUE TITLE
Unexpected lazy-loading, fetch behavior with multiple locales

### ISSUE THREAD

**Issue by tomsdob** [nuxt-modules/i18n#2185]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-nmhzwq-gudpmp

### Describe the bug

Unexpected translation behavior when using lazy-loaded translations with a fetch request and multiple locales.

### Additional context

I18n does not apply the current locale translations while in default locale - `'lv'`. The translations appear in `'en'` locale instead. 
In dev mode sometimes half of the translations are correct, half are wrong after hydration. 
In build mode all of the translations are wrong and don't respect the default locale.
Translation `id` param can be seen by using `?id=123` query in the URL.

**Comment by agracia-foticos** [comment]
same issue lazy load not runs!

**Comment by BobbieGoede** [comment]
It looks like there's a few things that could be causing the described behavior. I changed your reproduction to demonstrate the different configurations that could be at fault [here](https://stackblitz.com/edit/github-nmhzwq-xqfhnt?file=nuxt.config.ts,package.json).

The reproduction can be run with the following variations:
* `npm run dev` basically your original reproduction
* `npm run dev:no-browser-detect` this turns off browser language detection, which I think is causing the switching of languages in the first place
* `npm run dev:unique-file` this sets the locales to different locale files to check if caching is at issue (see the bottom info notice on this [doc page](https://v8.i18n.nuxtjs.org/guide/lazy-load-translations))
* `npm run dev:both` this combines the two adjustments above

It seems that the elements using `v-html` do not update whenever i18n variables are involved, I have added some elements to demonstrate this. When `detectBrowserLanguage` is enabled and the locale is changed, only plain variables in `v-html` are updated and variables inserted as normal using `{{ }}`.

When using `npm run dev:no-browser-detect` the elements using `v-html` do not seem to update and keep the translation of the language fetched on page load.

When using `npm run dev:unique-file` not much seems to change.

When using `npm run dev:both` it seems like switching between languages loads the correct translations. So far the issue seems to be caused by caching based on filename on combination with browser detection. And I think there may be something going wrong with `v-html` combined with i18n variables.

@kazupon should js/ts format locale files be cached by filename? The [example](https://v8.i18n.nuxtjs.org/guide/lazy-load-translations#basic-usage) shown in the docs could make it seem like using a single file is valid despite the info notice at the bottom.

**Comment by kazupon** [comment]
@BobbieGoede 

> @kazupon should js/ts format locale files be cached by filename? The example shown in the docs could make it seem like using a single file is valid despite the info notice at the bottom.

I think locale messages should be cached  if they are static, else they are dynamic, such as fetch locale mesasges via API or compose locale mesasges, they should not be cached.

A related issue is #2293. It may be necessary to support a `cache` key for `locales` optional objects.
For `js` or `ts` formats `cache` defaults to `false`, for `json`, `yaml`, and `json5` formats `cache` defaults to `true`.

**Comment by BobbieGoede** [comment]
This issue was resolved after adding configurable caching (and disabling cache by default for js/ts locale resources), and cannot be replicated with the latest release, so I'm closing it!
