### ISSUE TITLE
undesirable force render page

### ISSUE THREAD

**Issue by Vladoker** [nuxt-modules/i18n#2274]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.13
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-nmheyd?file=components%2FTheHeader.vue

### Describe the bug

It is expected that red counter will change if the language change occurs via header.

If you change the language using footer, the red counter changes as expected.

**Comment by BobbieGoede** [comment]
This is expected behaviour, the header uses navigation to change the language while the footer directly mutates the language without navigation. The counter gets reset because the index page is mounted again due to the navigation (it navigates from `index__en` to `index__fr`).

I recommend using either `switchLocalePath` or `setLocale` when switching languages to make sure routing updates/reflects the language switch.
