### ISSUE TITLE
Layout does not refresh when switching language

### ISSUE THREAD

**Issue by ghost** [nuxt-modules/i18n#2278]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.1
- Build Modules:    -
------------------------------

### Reproduction

StackBlitz: https://stackblitz.com/edit/github-pdyqtn-t7eyuv?file=layouts%2Fdefault.vue,pages%2Findex.vue

Switch the language in the reproduction: only the pages data is fetched for the new locale.

### Describe the bug

When using `useAsyncData` in a layout the data is only fetched on page load, but not when clicking the language switcher button.

**Comment by BobbieGoede** [comment]
The reason `useAsyncData` is called when switching to another language is because technically a different page is being loaded, `index___de` or `index___en` in this case, while the layout has already been loaded and setup. So switching language triggers the `setup()` of the index page, which means `useAsyncData` is called again.

You can add `{ watch: [locale] }` as options for the `useAsyncData` in your layout to have it run on `locale` change. I have changed your reproduction to demonstrate this [here](https://stackblitz.com/edit/github-pdyqtn-avkn8x?file=layouts%2Fdefault.vue,pages%2Findex.vue).

Since this is not exactly a bug I will be closing this issue, but please let me know if you have any questions!

**Comment by ghost** [comment]
@BobbieGoede Thanks for your answer. I’ve already tried `{ watch: [locale] }`, but the problem with this is, that the callback function in `useAsyncData` is executed even if there exists a payload with the same payload key. Especially when using in SSG mode, I don’t want the data to be fetched again. I have forked your stackblitz again, where now `nuxt generate` is run instead of `nuxt dev`. Everytime you switch the locale, the data is fetched.

https://stackblitz.com/edit/github-pdyqtn-sa3vsn?file=layouts%2Fdefault.vue

**Comment by FreekVR** [comment]
I've found similar issues in my app with the payloads.

The issue seems to be that the `locale` reactively switches before the `route` does. So if you're doing some reactiviy-based fetching on components that persist between routes, the payloads won't match with the correct URL and Nuxt gets "confused". I've also has mismatched content in this case (we need a reactive language value for our API calls)

I'm trying some workarounds and creating a new ticket for this, but this is a tentative repro of the issue:

```
const { currentCraftUri } = useCraft();
const route = useRoute();
const i18n = useI18n();

const locale = computed(() => {
    console.log(i18n?.localeProperties?.value);
    console.log(route.fullPath);
    return i18n?.localeProperties?.value?.myCustomProperty;
});
```

When using a language switcher similar to the one in the docs, you would see this computed trigger twice -- first with the new language and the old route, then again with the new language AND the new route. (tested on a static site with `nuxt generate && nuxt preview`)
