### ISSUE TITLE
Module fails to set langPath correctly when loaded via layer

### ISSUE THREAD

**Issue by marr** [nuxt-modules/i18n#2308]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.6.12`
- Builder:          `vite`
- User Config:      `modules`, `srcDir`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-rc.2`
- Build Modules:    `-`

### Reproduction

https://github.com/marr/i18n-srcDir-layer

`pnpm install`
`pnpm run dev`

See empty messages, even though the layer should have messages loaded.

### Describe the bug

In my layer, I have a non-default `srcDir` set. I don't see anything in the nuxt docs that say that is invalid.
When the app inheriting the layer is started, the `langPath` is set relative to the layer, but the messages are not loaded.

Further, if the parent app has an `i18n` section in the config, the resulting merge does not resolve the layer's langPath correctly. I believe the issue is around the layer containing a non-standard `srcDir`.

**Comment by BobbieGoede** [comment]
This has been fixed by #2290! You can try it out by installing the edge channel, I have changed your reproduction to demonstrate [here](https://stackblitz.com/edit/github-rbxhds?file=nuxt.config.ts,package.json). Please let me know if you are still experiencing this issue even with the edge channel installed.

**Comment by marr** [comment]
Thank you @BobbieGoede - appreciate the quick fix. Verified things behave great now.
