### ISSUE TITLE
Generated static app stops during loading animation

### ISSUE THREAD

**Issue by some-user123** [nuxt-modules/i18n#2334]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      ssr, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.3
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-owbijq

Important: `npm run generate` and `npm run preview`
(`npm run dev` is working fine)

### Describe the bug

Create a new nuxt app, add `@nuxtjs/i18n@8.0.0-rc.3`, define `strategy: "no_prefix"`, add a page called `[...slug].vue`.
Run `nuxt generate`, run `nuxt preview`: Browser is stuck during loading animation, can't even open devtools:
![image](https://github.com/nuxt-modules/i18n/assets/74715856/5b07cc2f-3242-49e8-951c-7a883e57009e)

**Comment by LordGaav** [comment]
Also applicable to our app, we also have `ssr: false` and `spaLoadingTemplate: "./assets/html/spa-loading-template.html"` set because we deploy as SPA only. Devtools in Firefox outright freeze, in Chrome I can enter them when I open them before navigating to the URL. Pauzing in the debugger reveals that the app seems to be stuck in a loop in the router that eats all CPU cycles.

We've noticed that one specific version of i18n-edge works properly with Nuxt 3.6.5: `@nuxtjs/i18n-edge@8.0.0-rc.2-28194444.5abd10b` . Any newer version shows the freeze as mentioned, but only in SPA mode. At least dev mode seems fine.
