### ISSUE TITLE
SyntaxError: Invalid regular expression: invalid group specifier name (Safari)

### ISSUE THREAD

**Issue by tjifyodor** [nuxt-modules/i18n#2848]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.1`
- Nuxt Version:     `3.11.0`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.9.4`
- Package Manager:  `pnpm@8.15.4`
- Builder:          `vite`
- User Config:      `devtools`, `ssr`, `builder`, `srcDir`, `nitro`, `vite`, `app`, `css`, `modules`, `i18n`, `components`
- Runtime Modules:  `@nuxtjs/i18n@8.2.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/fork/github/BobbieGoede/nuxt-i18n-starter/tree/v8
Opened on iOS <= 15

### Describe the bug

Regex lookahead/lookbehind is not supported on older safari browsers, [ufo@1.5.1](https://github.com/unjs/ufo) from the latest update, which is used as dependency, [added](https://github.com/unjs/ufo/commit/3910926c2666c8dafd193d6dd485cc7527d8ecbf#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R17) one, so project opened in older safari is not working anymore

**Comment by tjifyodor** [comment]
@BobbieGoede, I'm not sure if it is possible to create sharable reproduction for just a "starter template" running on a specific environment (iOS 15)

**Comment by BobbieGoede** [comment]
If this error is triggered in a plain starter template when opened in iOS 15, then even just a link to the starter template is sufficient, it's just to reduce the steps required for debugging as well as confirmation if any additional steps are required to reproduce the behavior.

But to be honest, `ufo` is installed and used by various dependencies upstream (`nuxt`, `nitropack` and more), aren't you running into this issue even without Nuxt I18n? I'm fine with tracking this issue here but it's likely not something we can work towards resolving in this module, I see it's also being tracked here https://github.com/unjs/ufo/issues/224.

**Comment by tjifyodor** [comment]
@BobbieGoede yes, you are right, looks like every nuxt package updated to ufo@1.5.1 have this issue, just wanted to be sure that its tracked somewhere

**Comment by pi0** [comment]
https://github.com/unjs/ufo/issues/224#issuecomment-2003701066
