### ISSUE TITLE
SEO attributes are not reactive (lang, dir html attribute) with no prefix strategy

### ISSUE THREAD

**Issue by jesspinklet** [nuxt-modules/i18n#2871]
### Discussed in https://github.com/nuxt-modules/i18n/discussions/2840

<div type='discussions-op-text'>

<sup>Originally posted by **jesspinklet** March 15, 2024</sup>
I have this in my app.vue for direction and language.
![image](https://github.com/nuxt-modules/i18n/assets/77070946/8e754891-64d2-4b02-a82a-d001b0104d61)

while using strategy **prefix** and changing the locale with `setLocale()` it will be updated 
as expected.

however, with `no prefix` strategy it seems it's not reactive or its not getting updated.

is this how it supposed to be? If yes, what's the best way to add a reactive lang and a dir attribute to html?</div>
Reproduction for this issue [link](https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-hexbdg?file=nuxt.config.ts)

**Comment by jesspinklet** [comment]
Reproduction for this issue [link](https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-hexbdg?file=nuxt.config.ts)

**Comment by BobbieGoede** [comment]
Thanks for the reproduction!

I see your comment in the config file and you're right, this is a bug caused by updating these attributes while only tracking for URL changes. For now I have a workaround for the `lang` and `dir` html attributes, I've updated your reproduction [here](https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-me3hj5?file=app.vue) to demonstrate.

Hopefully I'll have a fix ready soon!

**Comment by meirroth** [comment]
Experiencing the same issue in my project.
