### ISSUE TITLE
Module fetches wrong link when using server routes

### ISSUE THREAD

**Issue by alexieremia** [nuxt-modules/i18n#2898]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.5
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      modules, drupalCe, i18n
- Runtime Modules:  nuxtjs-drupal-ce@2.0.0-beta7, @nuxtjs/i18n@8.3.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qefmzw?file=nuxt.config.ts

### Describe the bug

When using server routes along with the latest i18n, changing the language results in a broken menu in some cases.

The server route code can be found at: https://github.com/drunomics/nuxtjs-drupal-ce/blob/2.x/src/runtime/server/api/menu.ts

When changing the language the first time it works and fetches with the correct URL `api/menu/api/menu_items/main`, but the second time it uses `/api/menu_items/main` (wrong URL) and fails.

To reproduce:
1. Go to the reproduction link
2. npm run dev
3. Click on "EN" 
4. Click back on "DE"
5. The menu fails
6. Check Network tab: `Error 500 /api/menu_items/main`

Please check and let me know if there's an issue with the implementation itself. Thank you!

**Comment by TurtlBbx** [comment]
@vloss3 I was able to resolve this issue in the nuxtjs-drupal-ce module code: https://github.com/drunomics/nuxtjs-drupal-ce/pull/220

Here is a Stackblitz that uses this fix (you need to clone it locally, Stackblitz won't install a branch build of the nuxtjs-drupal-ce module): https://stackblitz.com/edit/nuxt-starter-ngkqh7?file=package.json

**It turns out that this issue has nothing to do with the i18n module. So this issue can be closed.**
