### ISSUE TITLE
lazy:true doesn't work correctly

### ISSUE THREAD

**Issue by kominov** [nuxt-modules/i18n#2902]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.3.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-cro1om?file=locales%2Fen.json,locales%2Fru.json,nuxt.config.ts,app.vue,pages%2Findex.vue,components%2Fmenu.vue

### Describe the bug

I expect json with ru text will be loading only when i click ru locale. But instead, both files are downloaded at the same time
![image](https://github.com/nuxt-modules/i18n/assets/76279904/ad008d82-38b8-402b-9ede-9a96d63f6077)

**Comment by kazupon** [comment]
Thank you for your reporting!

Unfortunately, I could not reproduce this issue in my enviroment. 😞 

Your nuxt.config.ts has `defaultLocale: 'en'`.
When you access the root of the page only en.json is loaded.
If you switch to `ru` once and reload, both `en.json` and `ru.json` will be loaded. This behavior is correct. This behavior is correct, because the `defaultLocale: 'en'` and the switched `ru` are required.
