### ISSUE TITLE
Warn when using SEO features without configuring baseUrl

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/i18n#2941]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      modules, devtools, i18n
- Runtime Modules:  @nuxtjs/i18n@8.3.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-4wdrme?file=app.vue

### Describe the bug

Starting with v8.3.1 some trailing slashes disappeared, which leads to these invalid headers when using `useLocaleHead({ addSeoAttributes: true })`:

![image](https://github.com/nuxt-modules/i18n/assets/4778485/9987579b-36ee-4182-a129-f728ebe178d9)

Notice the empty `href`s, which should include `/` as they did before.

**Comment by BobbieGoede** [comment]
After looking into this again, you actually need to set a `baseUrl` (see https://i18n.nuxtjs.org/docs/guide/seo) since relative URLs for alternate links are not considered valid (according to Google https://developers.google.com/search/docs/specialty/international/localized-versions#all-method-guidelines).

We should probably add warnings if `baseUrl` is unset when using `addSeoAttributes` and perhaps disable the tags altogether if unset (in v9, as that would be breaking)

**Comment by dargmuesli** [comment]
You're right! I was just setting `baseUrl` in the `runtimeConfig` for `$production`, which was a mistake by me. Thank you for looking into this! A warning sounds like a great idea. If you want, you can rename this issue to fit the idea of adding a warning, or close this and create a new issue of course.
