### ISSUE TITLE
Nuxt plugin types break if I add i18n module

### ISSUE THREAD

**Issue by frasza** [nuxt-modules/i18n#3070]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.16.0
- Nuxt Version:     3.13.0
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      modules, devtools, compatibilityDate
- Runtime Modules:  @nuxtjs/i18n@8.5.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/frasza/plugin-type

### Describe the bug

I have axios plugin that provides its instance to the app and in case I add `@nuxtjs/i18n` to the nuxt config modules array, the plugin type becomes `unknown`.

**Comment by BobbieGoede** [comment]
This seems to kind of be caused by the i18n module, but I was able to reproduce it without as well as detailed in my comment on your other issue https://github.com/nuxt/nuxt/issues/28672#issuecomment-2306574692.

Not sure if this needs to be resolved on our end or on that of Nuxt's so I'll keep this open until we have further information 💪

**Comment by frasza** [comment]
Solved for me with latest patch release ♥️

**Comment by ThibaultVlacich** [comment]
I also have the issue with RuntimeConfig. As soon as `@nuxtjs/i18n` is added to the modules list, the return type of `useRuntimeConfig()` is `unknown`.

I'm trying to make a simple repro, but I'm failing to do so right now. But in my project, I've isolated the issue to come from @nuxtjs/i18n
