### ISSUE TITLE
Problem when used with AMP module (nuxt-i18n since version 6.13.5)

### ISSUE THREAD

**Issue by Manfies** [nuxt-modules/i18n#850]
### Version
nuxt-i18n: `6.13.5` - `6.13.9`
nuxt: `2.12.2`

#### [Mode](https://nuxtjs.org/api/configuration-mode):
- [X] universal
- [ ] spa

### Nuxt-i18n configuration
```
i18n: {
    parsePages: false,
    lazy: true,
    locales: [
      {
        territory: 'US',
        name: 'English',
        code: 'en',
        iso: 'en',
        file: 'en.json'
      },
      {
        territory: 'ES',
        name: 'Español',
        code: 'es',
        iso: 'es',
        file: 'es.json'
      },
    ],
    detectBrowserLanguage: false,
    vueI18n: {
      fallbackLocale: 'en'
    },
    vuex: {
      syncLocale: true,
      syncMessages: true
    },
    defaultLocale: 'en',
    langDir: 'locales/',
    seo: false
}
```

### Reproduction Link
[Sandbox](https://codesandbox.io/s/i18n-nuxt-module-issue-bo230?file=/nuxt.config.js)

### Steps to reproduce
1. Go to `/amp` route.
2. Go to `/amp/es` route.

### What is Expected?
When we follow the url with `/amp`, a page should open in the desired language with AMP support.

### What is actually happening?
Currently, when following the `/amp` path, it displays the language`ES`, although the default is `EN`. Also, if you try to go to the path `/amp/es` it will throw an error, although a Spanish AMP page should be open. Changing the version, I found the one that started it - `6.13.5`. If you change the version of `nuxt-i18n` package to `6.13.4` everything works fine with`/amp`.

**Comment by rchl** [comment]
It's a problem due to both this and amp module extending routes and things have changed in that regard in `nuxt-i18n` causing things to happen at different times.

I hate those kinds of issues...

@pi0 sorry for pinging you but do you have any input here? This issue with different modules extending routes at different times is hard to work with...
Also FYI @farnabaz

**Comment by pi0** [comment]
@rchl I think it is not something auto-magically resolvable by nuxt unless either of modules respects extending of routes from the other one. Specially this case where extending strategy is also different (amp adds `alias` but i18n adds new records) and we cannot guess it should be `/[locale]/[amp]` or `/[amp]/[locale]`) nor know which part of already extended route (string) is prefix and which part is real path to inject prefix.

One solution:
   - i18n module needs to also add `route.meta.locale` 
   - amp module can detect `locale` and take into account when creating aliases

**Comment by rchl** [comment]
The problem is that amp module extends routes using `Module. extendRoutes` from the module itself while I'm calling it from within 'build:before' hook. So my extending runs later while it needs to run first.

I'm not saying that this should automagically work but at least the user should be able to do something about it. For example by manually configuring module order. Unfortunately, that doesn't work anymore, since I've switched to the build hook for certain reasons...

I guess I'll have to refactor things again to fix that, but it would be good to have this issue at the back of the mind for potential addressing in future major Nuxt versions.

**Comment by rchl** [comment]
I guess some sort of rudimentary solution would be to extend `extendRoutes` to accept a "priority" argument which would result in callers being called in certain, preferred order.

**Comment by rchl** [comment]
Fix released in [v6.13.10](https://github.com/nuxt-community/i18n-module/releases/tag/v6.13.10)

The order should be back as before - will be decided by the order in which modules are registered.

**Comment by pi0** [comment]
@rchl Supporting a numeric order would introduce race-conditions between modules however. and yes i know regression caused because of delayed extendRoutes call. Thanks for quick fix :heart:  Will put an issue in nuxt3 to think about better integration.

**Comment by Manfies** [comment]
Hi @rchl. I have a small question about `nuxt-i18n` and `nuxt-redirect` modules. I think that it's issue, but i am not sure. I have updated the sandbox for reproduce. If you will try to get access to path `/foo` (or any other page that not existing) with current version of `nuxt-i18n` package (`6.13.10`) it will `Too many requests` error. But with version of package is`6.12.0` it works fine. What's really happening: every non-existent standard language page now has an error `Too many requests` instead of `404`, when we are using trailing slash at the end as default.

**Comment by rchl** [comment]
Could you create a separate issue for that? It would be better for tracking.

**Comment by Manfies** [comment]
@rchl Sure. 5-10 min.
