### ISSUE TITLE
[Feature request] Lazy load translation per page

### ISSUE THREAD

**Issue by AbdallahAlhaddad** [nuxt-modules/i18n#880]
#### The Problem:
As in the [documentation](https://i18n.nuxtjs.org/lazy-load-translations), a translation file can be added for any desired language (single translation file for the entire website), but this can be a performance/bandwidth hit for large websites that heavily use text. 

#### Suggested Solution:
I think it would be great if we can create `translation` directory that has a directory for every locale with the same structure as the Page directory as follows:

```bash
.
├── nuxt.config.js
├── pages
│   ├── about-us.vue
│   ├── blog
│   │   ├── index.vue
│   │   └── _slug.vue
│   ├── faq.vue
│   └── index.vue
└── Translations
    ├── en
    │   ├── about-us.js
    │   ├── blog
    │   │   ├── index.js
    │   │   └── _slug.js
    │   ├── faq.js
    │   └── index.js
    └── fr
        ├── about-us.js
        ├── blog
        │   ├── index.js
        │   └── _slug.js
        ├── faq.js
        └── index.js

```
and the module automatically bind each JavaScript file with its corresponding page for the current language when `lazy` & `filePerPage` are `true` as suggested below:
```js
//nuxt.config.js:

['nuxt-i18n', {
  locales: [
    {
      code: 'en',
      iso: '....',
      // file: 'en-US.js'  --> remove this when adding "filePerPage:true"
      folder: 'en'
      //....
    },
    {
      code: 'fr',
      folder: 'fr'
      iso: '....',
      //....
    }
  ],
  lazy: true,
  filePerPage: true,
  langDir: 'Translations/'
}]
```

**Comment by rchl** [comment]
1. I suppose one would also want to have common translations that would be available on all pages? Otherwise, would you duplicate them for each page?
2. If you have a big enough site that warrants this approach, wouldn't you be using some sort of translations managing service? And would such service be able to export in such a way that file names and directory structure is preserved?

I'm just trying to understand the usefulness of this approach better.
