### ISSUE TITLE
Handle 301 redirects when alwaysRedirect is set to true

### ISSUE THREAD

**Issue by JosefHjorth** [nuxt-modules/i18n#881]
I've renamed a few routes and would like to redirect the old route names to the new ones. However, since the alwaysRedirect is set to true, i18n picks up the current set locale and will add that to the route. 

I've implemented the 301 at the top in the i18n middleware;

```javascript
  if(route.fullPath == '/sv/old/route'){
    redirect(301, '/sv/new-route')
  }
```

For example;
/sv/old/route
should 301 to;
/sv/new-route

But if locale en is already set in a cookie, it will add /en/ to the route, resulting in;
/en/sv/new-route
and a page not found. 

What I would like is to have the locale set to sv and the route to be respected. 

I've tried to add both paths in the page view. Tried to use the setLocaleCookie right before the redirect. But can't get it to work. It still redirects again and I get the _Redirected_ when going from "/sv/old/route" to "/sv/new-route" via a navigation guard_ error.

**Comment by rchl** [comment]
I'm not sure exactly how you want it to work since `alwaysRedirect` means that it will always try to redirect to the locale stored in the cookie. And that's regardless if you have renamed some routes or not. So it basically makes switching to a route from another locale impossible unless you manually `setLocale` or `setLocaleCookie` first.

If you want me to have a closer look then you should create a simple repro.

BTW. #799 might be somewhat relevant here.
