### ISSUE TITLE
make iso prop available on $i18n object

### ISSUE THREAD

**Issue by timdiacon** [nuxt-modules/i18n#916]
### Is your feature request related to a problem? Please describe.

I need to send the iso code to my CMS to retrieve content in the correct language

### Describe the solution you'd like

make the iso code available directly on the $i18n object in the same way the locale code is

### Describe alternatives you've considered

As all the locales are available on the $i18n object as an array this can be filtered with the locale code to retrieve the corresponding iso code

**Comment by rchl** [comment]
Since locale objects accept any property, I wouldn't want to special-case the iso code as then someone could ask for some other to be exposed and in the end, it would only make sense to expose everything.

You can easily create a global mixin or inject the iso code through a separate plugin so I would consider that to be a viable and easy to implement alternative. Or just have a computed property if you need it only in one file.

**Comment by rchl** [comment]
Alternatively, I could expose a property like `$i18n.localeProperties` which would be a direct mapping to the object for current locale.

**Comment by timdiacon** [comment]
> Alternatively, I could expose a property like `$i18n.localeProperties` which would be a direct mapping to the object for current locale.

This would be perfect and I think make more sense that just exposing iso for the reasons you suggest 👍

**Comment by rchl** [comment]
`$i18n.localeProperties` property added in https://github.com/nuxt-community/i18n-module/releases/tag/v6.18.0
