### ISSUE TITLE
Trigger fallback when value is emptry

### ISSUE THREAD

**Issue by katerlouis** [nuxt-modules/i18n#946]
I use BabelEdit for managing my locale json files. A new item gets added to all json files. Good!
But that makes it very likely the editor forgets to add a translation. 

In that case `$t('some.nested.value')` will return an empty string. 

Is it possible to force nuxtI18n to use a fallback instead?

**Comment by rchl** [comment]
It seems like `BabelEdit` has an option to not save empty translations.

![Screenshot 2020-11-02 at 23 05 23](https://user-images.githubusercontent.com/153197/97924548-2208cc80-1d60-11eb-94ac-b29e8ccd2425.png)

**Comment by katerlouis** [comment]
Dude, I freakin love the internet.
Thank you very much :)

While this will work for my setup, not all devs in our team will probably use this tool.
So I'm still curious if we can force nuxt-i18n to (or vue-i18n for that matter) to fallback for empty values?

**Comment by rchl** [comment]
I'm not really planning to do anything to address this. I think the better approach is to make sure that the files are in the expected format in the first place. You could validate them from a commit hook for example.

Otherwise, you can try to play with defining custom fallback function through `vueI18n` options (https://i18n.nuxtjs.org/options-reference#vuei18n) but I'm not sure if you have access to all translations from there so it might require hacks).

**Comment by katerlouis** [comment]
😢

**Comment by rchl** [comment]
If you can find a clean solution for this then feel free to open a PR for consideration.
