### ISSUE TITLE
switchLocalePath does not work in layouts/error.vue

### ISSUE THREAD

**Issue by Iryna-L** [nuxt-modules/i18n#976]
Is it possible to switch language on error page (layout)?

It is known that the route must have a name for switching language. 
`function switchLocalePath (locale) {
  const name = this.getRouteBaseName()
  if (!name) {
    return ''
  }
}`
After redirect on the layouts/error.vue route does not have name.

How to handle this problem?

**Comment by rchl** [comment]
It should be possible to support that. Would need some changes in the module.

Or at least the module could attempt to generate a locale-specific path but that wouldn't guarantee that a route with such a path exists.

And it wouldn't work with "custom paths" as we currently need route base name to figure those out.

**Comment by FeixuRuins** [comment]
Any updates?

**Comment by rchl** [comment]
What are your use-cases exactly?

You want to change the locale on a 404 page or on other kinds of error pages?

This is not really that easy or even possible in some cases. While switching locale using `setLocale` API is already possible on error pages, switching using `NuxtLink` is likely not possible in all cases because we can't resend the same error to the route we want to switch to. If it would be just a 404 error then it would more or less work but for other kinds of errors not so much.

**Comment by DamianGlowala** [comment]
> What are your use-cases exactly?

Use case is simple and exactly the same as for all other translated pages on the website. If the user clicks a link leading to our page and the page no longer exists, they may want to switch the language of 404 information to the one they understand...

**Comment by FeixuRuins** [comment]
> What are your use-cases exactly?

I have a default layout with a footer (that applies to all pages). In that footer is a language switcher. It does nothing on error pages.

**Comment by rchl** [comment]
As I said, though, it depends on the kind of error if it's even possible to handle that.

If the page errors-out because of a failed axios request then navigating to another locale will re-load the page and that original error will be lost. The newly loaded page might trigger the same error or it might just load correctly.

So the part that I don't like about that is that the language switch could result in information loss.

I've also mentioned that switching locale through the `setLocale` API should work already. So it's possible to implement error-page-specific language switcher that would work without changing the URL.

**Comment by sscovil** [comment]
I was able to solve this by adding a click handler to my language selector. The click handler calls `setLocale`, but I also use the `:to` directive to update the URL (if applicable), using `switchLocalePath`.

My `LocaleMenu` component looks like this:

```
<template>
  <v-menu
    transition="slide-y-transition"
    offset-y
  >
    <template v-slot:activator="{ on, attrs }">
      <v-btn
        depressed
        v-bind="attrs"
        v-on="on"
        v-text="$i18n.localeProperties.name"
      />
    </template>
    <v-list>
      <v-list-item
        v-for="locale in $i18n.locales"
        :key="locale.code"
        :to="switchLocalePath(locale.code)"
        nuxt
        @click="$i18n.setLocale(locale.code)"
      >
        <v-list-item-title>{{ locale.name }}</v-list-item-title>
      </v-list-item>
    </v-list>
  </v-menu>
</template>

<script>
export default {
  name: 'LocaleMenu',
}
</script>
```

**Comment by BobbieGoede** [comment]
Closing this as v7 is not being actively worked on (critical hotfixes only), if this still applies to v8 and later please open a new issue!
